### ISSUE TITLE
 Microsoft.Azure.EventHubs 2.2.1 not compatible with Microsoft.Azure.Amqp 2.4.1

### ISSUE THREAD

**Issue by johnthcall** [Azure/azure-amqp#137]
I am running on .Net 4.7.2 with Microsoft.Azure.EventHubs 2.2.1, Microsoft.Azure.EventHubs.Processors 2.2.1. When using Microsoft.Azure.Amqp 2.3.7 the below code succeeds but after upgrading amqp to 2.4.1 the code crashes.

EventProcessorHost.RegisterEventProcessorFactoryAsync(IEventProcessorFactory factory, EventProcessorOptions processorOptions)

Microsoft.Azure.EventHubs.Processor.EventProcessorConfigurationException: Encountered error while fetching the list of EventHub PartitionIds ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Azure.Amqp, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Azure.EventHubs.Amqp.Management.AmqpServiceClient.<GetRuntimeInformationAsync>d__8.MoveNext()
   at Microsoft.Azure.EventHubs.Amqp.AmqpEventHubClient.<OnGetRuntimeInformationAsync>d__25.MoveNext()
   at Microsoft.Azure.EventHubs.EventHubClient.<GetRuntimeInformationAsync>d__30.MoveNext()
   at Microsoft.Azure.EventHubs.Processor.PartitionManager.<GetPartitionIdsAsync>d__6.MoveNext()
   at Microsoft.Azure.EventHubs.Processor.PartitionManager.<GetPartitionIdsAsync>d__6.MoveNext()
   at Microsoft.Azure.EventHubs.Processor.PartitionManager.<GetPartitionIdsAsync>d__6.MoveNext()
   at Microsoft.Azure.EventHubs.Processor.PartitionManager.<InitializeStoresAsync>d__10.MoveNext()
   at Microsoft.Azure.EventHubs.Processor.PartitionManager.<StartAsync>d__7.MoveNext()
   at Microsoft.Azure.EventHubs.Processor.EventProcessorHost.<RegisterEventProcessorFactoryAsync>d__53.MoveNext()

**Comment by serkantkaraca** [comment]
I was not able to repro the issue. EventHubs 2.2.1 loads Amqp 2.4 just fine. Can you start a new project and try send only scenario?

![image](https://user-images.githubusercontent.com/16924470/53976664-56744300-40bc-11e9-9f45-da5f5dfc0264.png)

**Comment by xinchen10** [comment]
@johnthcall There is no need to upgrade amqp to package 2.4.1 for .net framework. If you really want to, you may need a binding redirect in your app config.

**Comment by johnthcall** [comment]
It appears that the binding redirect was missing from my service, apologies for the false issue!
