### ISSUE TITLE
Transport.ClientWebSocketTransport.WriteAsyncCore fails in UWP applications

### ISSUE THREAD

**Issue by gmileka** [Azure/azure-amqp#142]
Repro:

- Create a UWP C# application. 
- Add Microsoft.Azure.Devices.Client 1.20.1.
- In MainPage.xaml, add a button to call `OnTest()`.
- In MainPage.xaml.cs, 

<pre>
using Microsoft.Azure.Devices.Client;
using System.Threading.Tasks;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;

namespace TestSDK_UWP
{
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        private async Task<MethodResponse> TestCallback(MethodRequest methodRequest, object userContext)
        {
            return new MethodResponse(200);
        }

        private async void Test()
        {
            _deviceClient = DeviceClient.CreateFromConnectionString("connections_tring",
                new ITransportSettings[]
                {
                    new AmqpTransportSettings(TransportType.Amqp_WebSocket_Only)
                    {
                        AmqpConnectionPoolSettings = new AmqpConnectionPoolSettings()
                    }
                });
            await _deviceClient.SetMethodHandlerAsync("TestMethod", TestCallback, null);
        }

        private void OnTest(object sender, RoutedEventArgs e)
        {
            Test();
        }

        DeviceClient _deviceClient;
    }
}

</pre>

Run the application on the desktop and invoke OnTest().

Actual:

<pre>
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnector.OpenConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnection(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.AmqpSessionCreator(DeviceIdentity deviceIdentity, ILinkFactory linkFactory, AmqpSessionSettings amqpSessionSettings, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass32_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass19_0.<<EnableMethodsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnableMethodsAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SetMethodHandlerAsync(String methodName, MethodCallback methodHandler, Object userContext, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SetMethodHandlerAsync(String methodName, MethodCallback methodHandler, Object userContext)
   at TestSDK_UWP.MainPage.Test()
</pre>

Microsoft.Azure.Amqp.Transport.ClientWebSocketTransport.WriteAsyncCore

**Comment by CIPop** [comment]
@Xin-Cheng PTAL this is blocking multiple Azure IoT customers and partners.

**Comment by xinchen10** [comment]
Do you have a repro using the library without the device client?

**Comment by CIPop** [comment]
@xinchen10 sorry, no  I don't have that and no time creating one. 
If I'm correctly reading into why you would want that is because of #120 and potential issues with the uap10 compiler?
You could try reproing by using the library within another very simple `netstandard2.0` library (nuget packaged) in a uap10 app.

/cc @gmileka

**Comment by CIPop** [comment]
@xinchen10 sorry - wrong link above. 

Yes we do with only WebSocket. We need to move this bug to corefx. @karelz @davidsh: this is the WebSocket+TLS failing the initial client certificate challenge even if the server is not requiring a client certificate. 

According to @davidsh in an offline thread, retrying the connection when this happens will fix the issue (WinINet issue).
