### ISSUE TITLE
Occasional service process crash : System.ObjectDisposedException

### ISSUE THREAD

**Issue by izvictor** [Azure/azure-amqp#176]
Hello ,
We have implemented a simple Event Hub message sender which is running as a windows service and occasionally we have the following error:
```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Threading.TimerQueueTimer.Change(UInt32, UInt32)
   at System.Threading.Timer.Change(Int64, Int64)
   at System.Threading.Timer.Change(System.TimeSpan, System.TimeSpan)
   at Microsoft.Azure.Amqp.AmqpSession+SessionChannel.DisposeDelivery(Microsoft.Azure.Amqp.Delivery, Boolean, Microsoft.Azure.Amqp.Framing.DeliveryState, Boolean)
   at Microsoft.Azure.Amqp.AmqpLink.DisposeDeliveryInternal(Microsoft.Azure.Amqp.Delivery, Boolean, Microsoft.Azure.Amqp.Framing.DeliveryState, Boolean)
   at Microsoft.Azure.Amqp.AmqpLink+<>c.<DisposeDelivery>b__56_0(Microsoft.Azure.Amqp.AmqpLink, Microsoft.Azure.Amqp.Delivery, Boolean, Microsoft.Azure.Amqp.Framing.DeliveryState, Boolean)
   at Microsoft.Azure.Amqp.AmqpLink.DoActionIfNotClosed[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`6<Microsoft.Azure.Amqp.AmqpLink,System.__Canon,Boolean,System.__Canon,Boolean,Boolean>, System.__Canon, Boolean, System.__Canon, Boolean)
   at Microsoft.Azure.Amqp.AmqpLink.DisposeDelivery(Microsoft.Azure.Amqp.Delivery, Boolean, Microsoft.Azure.Amqp.Framing.DeliveryState, Boolean)
   at Microsoft.Azure.Amqp.SendingAmqpLink+SendAsyncResult.CompleteOnTimer()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
which causes the process crash and stops the service.
Can you please help us in finding what could cause this kind of issue ?
Thank you.
Best regards.

**Comment by xinchen10** [comment]
It's a bug. The exception was unhandled on the timer thread. We will fix the bug. To workaround it now, you can set `AmqpSessionSettings.DispositionInterval = TimeSpan.Zero` when creating the session.

**Comment by izvictor** [comment]
Hello @xinchen10 ,
Thanks for you quick answer and for the workaround. Waiting forward for next release including the correction.
Best regards.
