### ISSUE TITLE
Unable to cast object of type 'Microsoft.Azure.Amqp.Framing.Accepted'

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-amqp#262]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#45055](https://github.com/Azure/azure-sdk-for-net/issues/45055).

### Please be aware that @JoeGaggler is the author of the original issue and include them for any questions or replies.

@xinchen10:  From what I can see, it doesn't look like there's any client logic in play here - it just calls `DeclareAsync` on the transaction controller.  _([src](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpTransactionEnlistment.cs#L41))_   This follows the same pattern that the T1 library used.  _([src](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Amqp/AmqpTransactionEnlistment.cs#L36))_

### Describe the bug

I am experiencing the same issue as reported in #14836 - however that issue is locked, and so I am refiling this bug.

Stacktrace:
```
System.InvalidCastException: Unable to cast object of type 'Microsoft.Azure.Amqp.Framing.Accepted' to type 'Microsoft.Azure.Amqp.Transaction.Declared'.
   at Microsoft.Azure.Amqp.Transaction.Controller.DeclareAsync(CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpTransactionEnlistment.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpTransactionManager.EnlistAsync(Transaction transaction, AmqpConnectionScope connectionScope, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(AmqpMessage batchMessage, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(AmqpMessage batchMessage, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<SendAsync>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
```

### Expected behavior

App code appears to be correct and is not throwing exceptions, so the expectation is that the ServiceBus library not throw either.

### Actual behavior

Exception is thrown and caught internally, but operations might not be succeeding.

### Reproduction Steps

```csharp
using (var transactionScope = new TransactionScope(TransactionScopeOption.RequiresNew, TransactionScopeAsyncFlowOption.Enabled))
{
	await receiver.SetSessionStateAsync(binaryData, cancellationToken);
	await serviceBusSender.SendMessageAsync(outMessage, cancellationToken); // THROWS HERE! Note: in and out have same session id
	await receiver.CompleteMessageAsync(inMessage, CancellationToken.None);
	transactionScope.Complete();
}
```

### Environment

Azure Container App
Base Image: mcr.microsoft.com/dotnet/aspnet:8.0

**Comment by jsquire** [comment]
Additional comment from @JoeGaggler:

> We have enabled `AzureEventSourceListener`, which logs these at the same time as the exceptions:

```
Forwarding Azure Event: 92, TransactionDischargeException, Azure-Messaging-ServiceBus, transactionId(String)=222d15f3-cb67-441a-a38f-516870a395f6:388, amqpTransactionId(String)=, exception(String)=Azure.Messaging.ServiceBus.ServiceBusException: TransactionID is null or empty Reference:69c73c38-5818-447c-8fdb-ca9f94602a04, TrackingId:781780e6-d9ad-47a2-95ea-dab3b67105aa_G28, SystemTracker:gtm, Timestamp:2024-07-17T16:22:13 (GeneralError). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
```

```
Forwarding Azure Event: 3, SendMessageException, Azure-Messaging-ServiceBus, identifier(String)={{{REDACTED}}}, exception(String)=System.InvalidCastException: Unable to cast object of type 'Microsoft.Azure.Amqp.Framing.Accepted' to type 'Microsoft.Azure.Amqp.Transaction.Declared'.
   at Microsoft.Azure.Amqp.Transaction.Controller.DeclareAsync(CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpTransactionEnlistment.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpTransactionManager.EnlistAsync(Transaction transaction, AmqpConnectionScope connectionScope, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(AmqpMessage batchMessage, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(AmqpMessage batchMessage, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<SendAsync>b__24_0>d.MoveNext()
```

```
Forwarding Azure Event: 89, TransactionInitializeException, Azure-Messaging-ServiceBus, transactionId(String)=222d15f3-cb67-441a-a38f-516870a395f6:388, exception(String)=System.InvalidCastException: Unable to cast object of type 'Microsoft.Azure.Amqp.Framing.Accepted' to type 'Microsoft.Azure.Amqp.Transaction.Declared'.
   at Microsoft.Azure.Amqp.Transaction.Controller.DeclareAsync(CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpTransactionEnlistment.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
```

**Comment by jsquire** [comment]
//fyi:  @EldertGrootenboer

**Comment by keir-nellyer** [comment]
We have seen this too.

We have a very similar set up to the original post. We are using scheduled messages, session state & deferred messages to power a retry mechanism. As such, we are using a `TransactionScope` to make these operations transactional.

We have seen this happen 7-8 times when processing a batch of 50,000 messages, some of which will have invoked this retry mechanism.

Another similar issue - https://github.com/Azure/azure-sdk-for-net/issues/14836

**Comment by xinchen10** [comment]
The Service Bus service team is investigating this issue.

**Comment by andyliuliming** [comment]
@xinchen10 any updates for this issue?

**Comment by JoeGaggler** [comment]
Checking in as it has been a few months. We still observe this error in Production a few times per day. It is recoverable, but would be great to have this fully resolved. If there is any diagnostic information that we can provide, please let me know. Thanks!

**Comment by vinaysurya** [comment]
Apologies @JoeGaggler  was a bit backlogged with other issues. Will look into this and reply this week.

**Comment by JoeGaggler** [comment]
Hi @vinaysurya - any luck tracking this down last week?

**Comment by JoeGaggler** [comment]
Hello @vinaysurya @xinchen10 @EldertGrootenboer - hoping to check in on this issue as it's been another couple months. Happy to provide any diagnostics that would be useful. Thanks!

**Comment by xinchen10** [comment]
The reason for the client side exception is that the response received from the service has unexpected type. @JoeGaggler I suggest you open a ticket with the product support to get faster response.

**Comment by werner-kellens** [comment]
I was investigating this error and came across this issue here. So the problem is still there and do you have any updates on this?

**Comment by JoeGaggler** [comment]
Update from MS on my support ticket is that there is no longer an ETA for a fix. No other details were provided, but was promised to be notified when there was new information.

**Comment by JoeGaggler** [comment]
I wanted to quickly share with the community that we are reverting our changes due to evidence that it causes silent data corruption of session state, likely in instances that it previously would have thrown the original transaction error. We are still investigating, but we have isolated it to the following steps (omitting irrelevant code):

```
// MESSAGE 1
await receiver.SetSessionStateAsync(binaryData, cancellationToken);
await receiver.CompleteMessageAsync(inMessage, CancellationToken.None);

// MESSAGE 2 (same session)
var state = await receiver.GetSessionStateAsync(cancellationToken);
```

The state fetched during message 2 is invalid.

The scenario is still extremely rare (3 **known** instances in 50,000+ sessions), but for us retrying a few failed transactions is much preferable to recovering from session state data corruption.

**Comment by JoeGaggler** [comment]
We have been working with Product Support and they determined that the issue from my previous comment was not related to this GitHub issue, and has since been resolved within Azure. With this info, we then resumed our transaction-free implementation, and have not had any `InvalidCastException`s since.
